export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_IMAGES_TO_POSTS = "FETCH_IMAGES_TO_POSTS";
export const SET_FILTERED_POSTS = "SET_FILTERED_POSTS";
export const ADD_POST_TO_FAVOURITES = "ADD_POST_TO_FAVOURITES";
export const REMOVE_POST_FROM_FAVOURITES = "REMOVE_POST_FROM_FAVOURITES";
